@startuml tableaublanc

hide footbox

box OrdinateurX
    participant "Utilisateur x"
    participant "Navigateur x"
end box

box OrdinateurN
    participant Utilisateur
    participant Navigateur
end box

box Serveur
    participant Kestrel
    participant MVC
    participant TableauBlanc
    participant Hub
    participant TableauBlancHub
end box

Utilisateur -> Navigateur : demande https://localhost:5001/
Navigateur -> Kestrel : GET /tableaublanc
Kestrel -> MVC : ressource /tableaublanc\nverbe GET
MVC -> TableauBlanc : Index
TableauBlanc --> MVC : code HTML de la page
MVC --> Kestrel : code HTML de la page
Kestrel --> Navigateur : code HTML de la page

loop Pour toute ressource du document HTML
    Navigateur -> Kestrel : GET /ressource
    Kestrel ->? : interroge le bon middleware
    ?--> Kestrel : contenu fichier
    Kestrel --> Navigateur : données de la ressource
end loop

Navigateur -> Kestrel : démarrer connexion /tableaublanchub
Kestrel -> Hub : démarrer connexion /tableaublanchub
Hub -> TableauBlancHub : OnConnectedAsync
TableauBlancHub -> Navigateur : exécuter "DemarrageTableau(lignes)"

...

== Dessin de l'utilisateur==
Utilisateur -> Navigateur : déplacement souris avec bouton enfoncé
Navigateur -> Kestrel : "DessinerLigne({"debut":..., "fin":...})"
Kestrel -> Hub : "DessinerLigne({"debut":..., "fin":...})"
Hub -> TableauBlancHub : DessinerLigne({"debut":..., "fin":...})
TableauBlancHub -> Hub : Appeler DessinerLigne({"debut":..., "fin":...}) pour tous les utilisateurs

loop Pour tous les utilisateurs x dont l'utilisateur original
    Hub -> "Navigateur x" : DessinerLigne({"debut":..., "fin":...})
end loop
@enduml