@startuml clients_classes
set namespaceSeparator ::

package M06_CasUtilisation_Clients {
    class ManipulationsClient {
        - m_depotClients : IDepotClients
        + ctor(p_depotClients : IDepotClients)
        + CreerClient(p_client : Client)
    }

    interface IDepotClients {
        + CreerClient(p_client : Client)
    }

    class Client {
        + Identifiant : Guid <<get; private set;>>
        + Prenom : string <<get; private set;>>
        + Nom : string <<get; private set;>>
        + Courriel : string <<get; private set;>>
        + NumeroTelephone : string <<get; private set;>>
        + ctor(p_identificant : Guid, p_prenom : string, p_nom : string, p_courriel : string, p_numeroTelephone : string)
    }

    ManipulationsClient -> IDepotClients
    ManipulationsClient ..> Client
    IDepotClients ..> Client
}

package M06_DAL_Client_SQLServeur {
    class DepotClientSQLServeur {
        + void CreerClient(p_client : Client)
    }

    class ClientSQLServeurDTO {
        + ClientSQLDTOId : Guid <<get; set;>>
        + Prenom : string <<get; set;>>
        + Nom : string <<get; set;>>
        + Courriel : string <<get; set;>>
        + NumeroTelephone : string <<get; set;>>
        + ctor(p_client : Client)
    }

    DepotClientSQLServeur ..|> M06_CasUtilisation_Clients::IDepotClients
    DepotClientSQLServeur .l> ClientSQLServeurDTO
}

together {
    package M06_MessageClient {
        class MessageClient {
            + Prenom : string <<get; set;>>
            + Nom : string <<get; set;>>
            + Courriel : string <<get; set;>>
            + NumeroTelephone : string <<get; set;>>
        }
    }

    package M06_Clients_Producteur {
        class Program

        Program ..> M06_MessageClient::MessageClient
    }

    package Rabbitmq.Client {}
}

package M06_Clients_Consommateur {
    class Program

    Program ..> M06_MessageClient::MessageClient
    Program ..> M06_CasUtilisation_Clients::ManipulationsClient
    Program ..> M06_CasUtilisation_Clients::IDepotClients
    Program .l> M06_DAL_Client_SQLServeur::DepotClientSQLServeur
}

M06_Clients_Producteur .[#blue]> Rabbitmq.Client
M06_Clients_Producteur .[#blue].> M06_MessageClient

M06_Clients_Consommateur .[#blue]> Rabbitmq.Client
M06_Clients_Consommateur .[#blue].> M06_CasUtilisation_Clients
M06_Clients_Consommateur .[#blue].> M06_MessageClient
M06_Clients_Consommateur .[#blue]l> M06_DAL_Client_SQLServeur

@enduml
