@startuml Beneficiaires_packages

package M06_CasUtilisation_Beneficiaires {

}

package M06_DAL_Beneficiaire_SQLServeur {
   
}

M06_DAL_Beneficiaire_SQLServeur ..> M06_CasUtilisation_Beneficiaires

package M06_MessageBeneficiaire {
   
}

package M06_Beneficiaire_Producteur {

}
M06_Beneficiaire_Producteur ..> M06_MessageBeneficiaire

package M06_Beneficiaire_Consommateur {


}
M06_Beneficiaire_Consommateur ..> M06_MessageBeneficiaire
M06_Beneficiaire_Consommateur ..> M06_CasUtilisation_Beneficiaires
M06_Beneficiaire_Consommateur ..> M06_DAL_Beneficiaire_SQLServeur

package M06_Entite_Beneficiaires{}

M06_Beneficiaire_Consommateur .left.> M06_Entite_Beneficiaires
M06_CasUtilisation_Beneficiaires .left.> M06_Entite_Beneficiaires
M06_Beneficiaire_Producteur .left.> M06_Entite_Beneficiaires
M06_CasUtilisation_Beneficiaires .left.> M06_Entite_Beneficiaires
M06_DAL_Beneficiaire_SQLServeur .left.> M06_Entite_Beneficiaires

package Rabbitmq.Client {

}


M06_Beneficiaire_Producteur ..> Rabbitmq.Client
M06_Beneficiaire_Consommateur ..> Rabbitmq.Client

@enduml
