@startuml
set namespaceSeparator ::

namespace DSED_M01_Fichiers_Texte {
    class Program {
        {static} Main(args:string[]) : void
    }
}

namespace M01_Srv_Municipalite << srvm >> {
    class Municipalite {
        + CodeGeographique : int <<get>> <<set>>
        + NomMunicipalite : string <<get>> <<set>>
        + AdresseCourriel : string? <<get>> <<set>>
        + AdresseWeb : string? <<get>> <<set>>
        + DateProchaineElection : datetime? <<get>> <<set>>
        + <<override>> Equals(obj : object) : bool
        + <<override>> GetHashCode() : int
    }

    interface IDepotMunicipalites {
        + ChercherMunicipaliteParCodeGeographique(p_codeGeographique : int) : Municipalite
        + ListerMunicipalitesActives() : IEnumerable<Municipalite>
        + DesactiverMunicipalite(p_municipalite : Municipalite) : void
        + AjouterMunicipalite(p_municipalite : Municipalite) : void
        + MAJMunicipalite(p_municipalite : Municipalite) : void
    }

    class StatistiquesImportationDonnees {
        + NombreEnregistrementsAjoutes : int <<get>> <<set>>
        + NombreEnregistrementsModifies : int <<get>> <<set>>
        + NombreEnregistrementsDesactives : int <<get>> <<set>>
        + NombreEnregistrementsNonModifies : int <<get>> <<set>>
        + NombreMunicipalitesImportees : int <<get>> <<set>>
        + <<override>> ToString() : string
    }

    interface IDepotImportationMunicipalites {
        LireMunicipalites() : IEnumerable<Municipalite>
    }

    class TraitementImporterDonneesMunicipalite {
        + ctor(p_depotImportationMunicipalites : IDepotImportationMunicipalites, p_depotMunicipalites : IDepotMunicipalites)
        + Executer() : StatistiquesImportationDonnees
    }

    IDepotImportationMunicipalites -[hidden]-> IDepotMunicipalites
    IDepotMunicipalites -[hidden]-> StatistiquesImportationDonnees
    StatistiquesImportationDonnees -[hidden]-> TraitementImporterDonneesMunicipalite
}

namespace M01_DAL_Municipalite_MySQL {
    class DepotMunicipalitesMySQL {
        + ctor(p_contexte : MunicipaliteContextMySQL)
        + AjouterMunicipalite(p_municipalite : srvm.Municipalite) : void
        + ChercherMunicipaliteParCodeGeographique(p_codeGeographique : int) : srvm.Municipalite
        + DesactiverMunicipalite(p_municipalite : srvm.Municipalite) : void
        + ListerMunicipalitesActives() : IEnumerable<srvm.Municipalite>
        + MAJMunicipalite(p_municipalite : srvm.Municipalite) : void
    }

    DepotMunicipalitesMySQL --|> M01_Srv_Municipalite::IDepotMunicipalites

    class Municipalite {
        + MunicipaliteId : int <<get>> <<set>>
        + NomMunicipalite : string <<get>> <<set>>
        + AdresseCourriel : string? <<get>> <<set>>
        + AdresseWeb : string? <<get>> <<set>>
        + DateProchaineElection : datetime? <<get>> <<set>>
        + Actif : bool <<get>> <<set>>
        + ctor()
        + ctor(p_municipalite : srvm.Municipalite)
        + VersEntite() : srvm.Municipalite
    }

    class MunicipaliteContextMySQL {
        + MUNICIPALITES : DbSet<Municipalite>? <<get>> <<set>>
        + ctor(options : DbContextOptions<MunicipaliteContextMySQL>)
        # <<override>> OnConfiguring(p_optionBuilder : DbContextOptionsBuilder) : void
    }

    MunicipaliteContextMySQL -[hidden]-> Municipalite
    Municipalite -[hidden]-> DepotMunicipalitesMySQL
}


namespace M01_DAL_Import_Munic_CSV {
    class DepotImportationMunicipaliteCSV {
        + ctor(p_nomFichierAImporter : string)
        + LireMunicipalites() : IEnumerable<Municipalite>
    }

    DepotImportationMunicipaliteCSV ..|> M01_Srv_Municipalite::IDepotImportationMunicipalites
}

namespace M01_DAL_Import_Munic_JSON {
    class DepotImportationMunicipaliteJSON {
        + ctor(p_nomFichierAImporter : string)
        + LireMunicipalites() : IEnumerable<Municipalite>
    }
    
    DepotImportationMunicipaliteJSON ..|> M01_Srv_Municipalite::IDepotImportationMunicipalites
}

DSED_M01_Fichiers_Texte .> M01_DAL_Import_Munic_JSON
DSED_M01_Fichiers_Texte ..> M01_DAL_Import_Munic_CSV
DSED_M01_Fichiers_Texte ..> M01_DAL_Municipalite_MySQL
DSED_M01_Fichiers_Texte ..> M01_Srv_Municipalite
M01_DAL_Import_Munic_CSV ..> M01_Srv_Municipalite
M01_DAL_Import_Munic_JSON ..> M01_Srv_Municipalite
M01_DAL_Municipalite_MySQL ..> M01_Srv_Municipalite
M01_DAL_Municipalite_MySQL::MunicipaliteContextMySQL -u-|> System.Data.Entity::DbContext

@enduml
