// <auto-generated />
using System;
using M01_DAL_Municipalite_MySQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSED_M01_Fichiers_Texte.Migrations
{
    [DbContext(typeof(MunicipaliteContextMySQL))]
    partial class MunicipaliteContextMySQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("M01_DAL_Municipalite_MySQL.Municipalite", b =>
                {
                    b.Property<int>("MunicipaliteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AdresseCourriel")
                        .HasColumnType("text");

                    b.Property<string>("AdresseWeb")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateProchaineElection")
                        .HasColumnType("datetime");

                    b.Property<string>("NomMunicipalite")
                        .HasColumnType("text");

                    b.HasKey("MunicipaliteId");

                    b.ToTable("Municipalites");
                });
#pragma warning restore 612, 618
        }
    }
}
