@startuml
set namespaceSeparator ::

package DSED_M05_SOAP_Web {
    namespace Entite {
        class Municipalite {
            + int CodeGeographique << get; private set; >>
            + string NomMunicipalite << get; private set; >>
            + string AdresseCourriel << get; private set; >>
            + string AdresseWeb << get; private set; >>
            + DateTime DateProchaineElection << get; private set; >>
            + bool Actif << get; private set; >>
            + Municipalite(int p_codeGeographique, string p_nomMunicipalite, string p_adresseCourriel, string p_adresseWeb, DateTime p_dateProchaineElection, bool p_actif)
            + public override bool Equals(object obj)
            + <<override>> int GetHashCode()
            + static bool operator ==(Municipalite left, Municipalite right)
            + static bool operator !=(Municipalite left, Municipalite right)
        }

        interface IDepotMunicipalites {
            + Municipalite ChercherMunicipaliteParCodeGeographique(int p_codeGeographique)
            + IEnumerable<Municipalite> ListerMunicipalitesActives()
            + void DesactiverMunicipalite(Municipalite p_municipalite)
            + void AjouterMunicipalite(Municipalite p_municipalite)
            + void MAJMunicipalite(Municipalite p_municipalite)
        }
    }

    namespace CasUtilisation {
        class ManipulationMunicipalites {
            - IDepotMunicipalites m_depotMunicipalites;
            + ManipulationMunicipalites(IDepotMunicipalites p_depotMunicipalites)
            + IEnumerable<Municipalite> ObtenirListeMunicipalites()
            + Municipalite ObtenirMunicipalite(int p_codeGeographique)
            + void CreerMunicipalite(Municipalite p_municipalite)
            + void ModifierMunicipalite(Municipalite p_municipalite)
            + void SupprimerMunicipalite(Municipalite p_municipalite)
        }
        note top of ManipulationMunicipalites: Cette classe permet d'avoir un traitement spécifique par cas d'utilisation\n(Algorithme). Ici, chaque méthode pourra appeler directement le dépot.
    }
    
    namespace PresentationServiceSOAP {
        class MunicipaliteService {
            - m_manipulationMunicipalites : ManipulationMunicipalites;
            + MunicipaliteService(ManipulationMunicipalites p_manipulationMunicipalites)
            + IEnumerable<MunicipaliteSOAPDTO> ObtenirListeMunicipalites()
            + MunicipaliteSOAPDTO ObtenirMunicipalite(int p_codeGeographique)
            + void CreerMunicipalite(MunicipaliteSOAPDTO p_municipalite)
            + void ModifierMunicipalite(MunicipaliteSOAPDTO p_municipalite)
            + void SupprimerMunicipalite(MunicipaliteSOAPDTO p_municipalite)
        }
        note top of MunicipaliteService: Cette classe permet d'exposer ManipulationMunicipalites. Il ne doit pas faire de\nmanipulation algorithmiques autres que des conversions de types et des validations\nd'entrées. Elle ne fait que présenter les méthodes.
    }

    namespace Persistance {
        class MunicipaliteSQLDTO {
            + int MunicipaliteSQLDTOId << get; set; >>
            + string NomMunicipalite << get; set; >>
            + string AdresseCourriel << get; set; >>
            + string AdresseWeb << get; set; >>
            + DateTime DateProchaineElection << get; set; >>
            + bool Actif << get; set; >>
            + MunicipaliteSQLDTO(Municipalite p_entite)
            + Municipalite VersEntite()
        }
        note top of MunicipaliteSQLDTO: Propriétés et format adaptés à Entity Framework Core
        
        class DepotMunicipalitesSQL {
            - m_contexte : ApplicationDbContext
            + DepotMunicipalitesSQL(ApplicationDbContext : m_contexte)
            + Municipalite ChercherMunicipaliteParCodeGeographique(int p_codeGeographique)
            + IEnumerable<Municipalite> ListerMunicipalitesActives()
            + void DesactiverMunicipalite(Municipalite p_municipalite)
            + void AjouterMunicipalite(Municipalite p_municipalite)
            + void MAJMunicipalite(Municipalite p_municipalite)
        }
        class ApplicationDbContext {
            ...
            + DbSet<MunicipaliteSQLDTO> Municipalite <<get; set;>>
        }

    DepotMunicipalitesSQL .> MunicipaliteSQLDTO
    DepotMunicipalitesSQL .u.> ApplicationDbContext
    }

    class Startup {}

    class Program {
        + {static} int main(string[] argv)
    }

    Program ..> Startup
    Startup ..> Persistance::DepotMunicipalitesSQL
    Startup .> Persistance::ApplicationDbContext
    Startup ..> Entite::IDepotMunicipalites
    Startup ..> CasUtilisation::ManipulationMunicipalites
    Startup ..> PresentationServiceSOAP::MunicipaliteService
    CasUtilisation::ManipulationMunicipalites --> Entite::IDepotMunicipalites
    CasUtilisation::ManipulationMunicipalites ..> Entite::Municipalite
    PresentationServiceSOAP::MunicipaliteService -> CasUtilisation::ManipulationMunicipalites
    Persistance::DepotMunicipalitesSQL .|> Entite::IDepotMunicipalites
    Persistance::DepotMunicipalitesSQL ..> Entite::Municipalite
}

together {
    package DSED_M05_SOAP_Model {
        interface IMunicipaliteService {
            + IEnumerable<MunicipaliteSOAPDTO> ObtenirListeMunicipalites()
            + MunicipaliteSOAPDTO ObtenirMunicipalite(int p_codeGeographique)
            + void CreerMunicipalite(MunicipaliteSOAPDTO p_municipalite)
            + void ModifierMunicipalite(MunicipaliteSOAPDTO p_municipalite)
            + void SupprimerMunicipalite(MunicipaliteSOAPDTO p_municipalite)
        }
        note left of IMunicipaliteService: Va avoir des attributs\nServiceContract et\nOperationContract
    
        class MunicipaliteSOAPDTO {
            + int CodeGeographique << get; set; >>
            + string NomMunicipalite << get; set; >>
            + string AdresseCourriel << get; set; >>
            + string AdresseWeb << get; set; >>
            + DateTime DateProchaineElection << get; set; >>
            + bool Actif << get; set; >>
        }
        note left of MunicipaliteSOAPDTO: Propriétés et format\nadaptés aux clients\ndu service SOAP
    
        IMunicipaliteService ..> MunicipaliteSOAPDTO
    }
    
    package DSED_M05_SOAP_ExempleClientConsole {
        class Program {
            + {static} int main(string[] argv)
        }
    }
}

DSED_M05_SOAP_Web::Startup .> DSED_M05_SOAP_Model::IMunicipaliteService
DSED_M05_SOAP_Web::PresentationServiceSOAP::MunicipaliteService .|> DSED_M05_SOAP_Model::IMunicipaliteService
DSED_M05_SOAP_Web::PresentationServiceSOAP::MunicipaliteService ..> DSED_M05_SOAP_Model::MunicipaliteSOAPDTO
DSED_M05_SOAP_ExempleClientConsole::Program ..> DSED_M05_SOAP_Model::IMunicipaliteService
@enduml
